### ISSUE TITLE
Asset browser search limitation

### ISSUE THREAD

**Issue by KoalaNalle** [Traderain/Wolven-kit#103]
There's a search limitation that asset browser can find. 

One example is the eye meshes ingame. There are 400 of them. WolvenKit asset browser finds. About 150 of the. 

All eye meshes are named "he_xxxxxx.w2mesh"

**Comment by Traderain** [comment]
That's really weird. 
![image](https://user-images.githubusercontent.com/6411732/45575429-c9220580-b873-11e8-8d45-8e9c148a8586.png)
```csharp
found.GroupBy(file => file.Item2.Name).Select(g => g.First()).ToList().Count
```
> 539

**Comment by rfuzzo** [comment]
Cannot replicate the result (all meshes are found), but it might be related to the fact that the asset browser limits the display to 1000 items.
