### ISSUE TITLE
WCC_Lite crash on edited file: CRC error

### ISSUE THREAD

**Issue by KoalaNalle** [Traderain/Wolven-kit#109]
Any edited file will become CRC-corrupted.

Easily checked with "wcc_lite dumpfile" as it will result in CRC error, and the dump fails.

**Comment by Traderain** [comment]
Solution: https://github.com/Lim3zer0/CR2WTools/blob/3d2d55652ccddfff28d18510e392c26e437fda57/CR2W/IO/CR2WBinaryWriter.cs#L343

**Comment by Lim3zer0** [comment]
Can use this:
https://gist.github.com/Lim3zer0/33f382ddf3cfefca0b00af9f62050393

**Comment by Traderain** [comment]
> Can use this:
> https://gist.github.com/Lim3zer0/33f382ddf3cfefca0b00af9f62050393

I implemented it offline but I don't really like it that we write the file twice and I can't find the proper crc32 class for it. I will try to work from this and fix the header calculations.
