### ISSUE TITLE
Custom sized "Marked files:" area in asset browser

### ISSUE THREAD

**Issue by KoalaNalle** [Traderain/Wolven-kit#112]
It would be nice if the "Marked Files:" section could be resizeable, also that the sizes and positions would be saved, at least within the mod, maybe globally.

![wolvenkit_assetbrowserrequest](https://user-images.githubusercontent.com/34051683/46272483-dfa9ab80-c559-11e8-8b56-7775cd4d31b2.JPG)

**Comment by Traderain** [comment]
Gonna try to figure out how to redesign this since we want to have a preview in there somewhere as well.

**Comment by rfuzzo** [comment]
added a simple spit box. 
![image](https://user-images.githubusercontent.com/37657287/50954821-67834800-14af-11e9-96ec-7d6cea1a6f7f.png)

Where were you thinking of displaying the preview? I guess you were thinking texture preview?

**Comment by Traderain** [comment]
texture preview, play sounds, preview xml etc, open renderer to make sewrching for stuff easier
