### ISSUE TITLE
Separate main form into multiple files

### ISSUE THREAD

**Issue by Traderain** [Traderain/Wolven-kit#115]
We are getting to the point where frmMain.cs takes 30s to open and has like 5k lines of code.
We should have separate files like:
- Hotkeys.cs
- Menu.cs
etc.
And have those controll separate parts of the application.
I was thinking about moving the whole thing to wpf but I am not sure if that's worth the hassle.

**Comment by shivangupadhyay05** [comment]
Sir , where is this file frmMain.cs . help me locating it .

**Comment by Traderain** [comment]
@shivangupadhyay05 https://github.com/Traderain/Wolven-kit/blob/master/WolvenKit/Forms/frmMain.cs

**Comment by shivangupadhyay05** [comment]
Thank you Sir for yo help !
