### ISSUE TITLE
Asset browser search skips files

### ISSUE THREAD

**Issue by Murzinio** [Traderain/Wolven-kit#116]
**Describe the bug**
Asset browser search skips many srt files. (possibly other extensions as well)

**To Reproduce**
1. Go to Asset browser.
2. Search for srt files.
3. Compare available srts with the list grabbed by my tool from all bundles:
https://pastebin.com/qz1BKA77 
The grass folder is missing for example.

**Expected behavior**
A complete list of srts, including grasses etc.

**Comment by rfuzzo** [comment]
Items only appear missing, since the asset browser limits the dispaly results to 1000. All files are in fact found. 
But, an asset browser with a paging feature might be good.
