### ISSUE TITLE
CR2W compile bug

### ISSUE THREAD

**Issue by vonLeebpl** [Traderain/Wolven-kit#143]
**Describe the bug**
CR2W build crushes with:
>CSC : error CS2001: Source file 'D:\Repos\Wolven-kit\WolvenKit.CR2W\Types\W3\ISerializable\IScriptable\CObject\CResource\CFont.cs' could not be found.

CFonts is included in solution definition but it's not present in repository.
Either is not needed or repo is buggy.

**To Reproduce**
1. Try rebuild solution.

**Comment by vonLeebpl** [comment]
Can be closed now. If Cfont.cs is not used any more.

**Comment by Traderain** [comment]
Repo is buggy. @rfuzzo forgot to commit it. Will be resolved asap. Thanks for the report.

**Comment by rfuzzo** [comment]
closed with #144
