### ISSUE TITLE
XML dump beautification + chunks dump.

### ISSUE THREAD

**Issue by vonLeebpl** [Traderain/Wolven-kit#145]
I saw a discussion on xml file dump beautification. I can take it.

At first I will beautify existing dump with new lines and tabs. There is also a need to disable xml dump option for xml files.

Next I plan to create additional option in context menu to dump chunks only with variables in readable format that users will be able to compare for example 2 dumps in WinMerge.

- [x] Beautify existing dump
- [x] Fix xml dump menu context
- [x] Create chunks with variables xml dump

**Comment by rfuzzo** [comment]
sounds great! thanks for doing it. the shoddy xml dump I wrote was just for testing - would be great if we had a real way to serialize and deserialize cr2w - be it xml json or sthg else.

**Comment by vonLeebpl** [comment]
Or add virtual serialization method to CVariable. I'm not sure yet how to handle recurrence as GetEditableVariables() is a method not property.
Any advice welcome.

**Comment by vonLeebpl** [comment]
Not the prettiest, but for modders maybe usefull to be able to create patches and easily find differences between files.

**Comment by Traderain** [comment]
> Not the prettiest, but for modders maybe usefull to be able to create patches and easily find differences between files.

I think it is sufficient for the task. Thanks for the contribution :)
