### ISSUE TITLE
Automatically expand Value field

### ISSUE THREAD

**Issue by teijiIshida** [Traderain/Wolven-kit#157]
**Is your feature request related to a problem? Please describe.**
Yes, when editing files, especially w2ent and w2mesh files, it's really annoying and tiresome to have to expand it every time I open the files. See pictures under additional context.

**Describe the solution you'd like**
I would like to propose making it automatically expand the middle field, which is usually the field modders need to work with a lot. It can expand based on Wolvenkit's windows size, until the third field can't be pushed any further without making it disappear (requiring horizontal scroll). See pictures under additional context for clearer example.

**Describe alternatives you've considered**
If the above can't be done, then just automatically expanding the middle field until it reaches full viewable without having to manually expand it would be good too.

**Additional context**
Pics: https://imgur.com/a/XAOtocB

**Comment by Traderain** [comment]
Good idea! Will be implemented once we have time.

**Comment by Traderain** [comment]
This would be the best solution probably: https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.columnheader.width?redirectedfrom=MSDN&view=netframework-4.8#remarks so everytime everything is expanded as much is it can.
