### ISSUE TITLE
search by keyword for 3d asset

### ISSUE THREAD

**Issue by rmemr** [Traderain/Wolven-kit#19]
As a 3d asset modder I want to search by keyword for a specific 3d assets so I can select it for further usage (e.g. 3d preview, export, etc.)

- search should be integrated in the overview list
- case insensitive
- number of found vs total number should be always visible
- key for resetting the search

**Comment by Traderain** [comment]
@rmemr I was thinking rather to add file preview to bundle explorer. Since you can already search in that. Untill we have proper level renderer which is waaaay down the list I think that will be sufficient.

**Comment by Traderain** [comment]
This should have been closed since #87
