### ISSUE TITLE
Dump game assets crashes

### ISSUE THREAD

**Issue by Maxzor** [Traderain/Wolven-kit#192]
**Describe the bug**
Hello, I have 4 hours in W3 modding.
AFAIK tool "dump game assets" does "wcc_lite uncook" but better?
It crashes : https://pastebin.com/h5psa7nK

Edit : any documentation would be awesome!
I can lend a hand provided you setup TODO starter topics.

**Comment by Maxzor** [comment]
Double backslashes in file paths generated by UI maybe?

**Comment by Maxzor** [comment]
It's actually 'wcc_lite dumpfile' that fails.

**Comment by Maxzor** [comment]
If wcc_lite poor piece of software, and is slower than wk to dump, why not get rid of the WCC wrapper completely and do things in-house?

**Comment by rfuzzo** [comment]
Removed dump game assets completely, in favor of the now-integrated ModKit
It is as easy to use, since it supports dragging & droping of project folders into the ModKit arguments
We also have the xr2w-to-text option creating yaml-style files with more info than wcc.
