### ISSUE TITLE
Rewording class and variable names

### ISSUE THREAD

**Issue by Maxzor** [Traderain/Wolven-kit#196]
Trying to make terminology more accessible to newcomers :
**************** Those two are interfaces that are not intuitive. I chose external/internal to describe where you look at.
@rfuzzo  proposes 1 IWitcherArchiveManager 2 IWitcherArchive. Rmemr talked about Virtual file system.
 - [ ]  IWitcherArchive --> IInternalWitcherArchive
 - [ ]  IWitcherArchiveType --> IExternalWitcherArchive + FileName --> ExternalAbsoluteArchivePath

This is PR #197 
Or rather WitcherArchive(External|Internal / Outboud|Inbound)Interface ?

WIP, will be separate PR, harder
**************** Next 3 is about un-mengling properties between classes, so as to not get lost in similar variable names.
 - [ ]  CR2W.FileName -->CR2W.CR2WFileName
 - [ ]  IWitcherFile.Name --> IWitcherFile.InternalAbsoluteFilePath
 - [ ]  W3Mod various renames - nothing much - Edit : abandoned, would have broken existing mod proj files or necessitated tedious serialization mapping.
**************** This needs quite extensive testing, I made only simple ones. 

 - [ ]  replace "bundle" stack variable names by archive when it is not only bundle dealt with. This is about finding another term than "bundle" to describe general packed files that are not only bundles.

**Comment by rfuzzo** [comment]
suggestion from yesterday: 
IWitcherArchiveType -> IWitcherArchive
IWitcherArchive -> IManager

**Comment by Maxzor** [comment]
IWitcherArchiveOutbound
IWitcherArchiveInbound
