### ISSUE TITLE
Feature request : game-file diff pane

### ISSUE THREAD

**Issue by Maxzor** [Traderain/Wolven-kit#198]
**Is your feature request related to a problem? Please describe.**
I am frustrated that some mods on nexusmods do not provide source code.
They modify vanilla game files that are not off-the-shelf human-readable :
it is a pain in the ass to diff changes, and get to a precise understanding of what those third-party mods do.

**Describe the solution you'd like**
Wkit's git-diff pane. Visual diff of the xml/csv/a_readable_format of two version of a game file.

**Describe alternatives you've considered**
[Script merger](https://github.com/IDCs/WitcherScriptMerger), did not look much into it.
And it is not the same perimeter. It is a merge tool, this is a tad too high of an ambition for wkit currently but a diff feature is not AFAIU.

Long-term goal would be to predate its whole functionality.

**Comment by Traderain** [comment]
Isn’t the modexplorer enough? I mean you can already extract the files from the mod. Mod merger can show what is changed and conflicting. Doesn’t really worth the effort imo, maybe we can kdiff the dumped cr2w files if someone really needs it

**Comment by Maxzor** [comment]
It could be useful, if wolvenkit ever becomes a mod merging manager, to look at diffs between i.e. two versions of the same w2ent file changed by different mods, and to merge/rebase from wkit, without having to dump files to xml.

**Comment by Maxzor** [comment]
Maybe better to not loose time reinventing the wheel

SCM and Transforms... TL;DR no need for wkit merge
@freenode#git :
```
<maxzor> Hello, I know that you can add hooks to git to read xlsx files.
<maxzor> (Their xml data)
<maxzor> Can you add multiple levels of hooks to read files compressed multiple times?
<osse> maxzor: are you talking about filters here and not hooks?
<maxzor> Like this https://github.com/scholer/ooxml-git-hooks
<rafasc> looks like they're using the wrong tool to solve this problem.
<maxzor> How are you putting office files on git in the first place then?
<osse> git add foo.docx ?
<osse> that's what I would do
<maxzor> but that will be binary diffs
<rafasc> you can store it as binaries, and define a textconv script to show textual diffs.
<rafasc> No hooks necessary, but seems that tool is mangling the documents into another format to be stored.
<maxzor> rafasc, can you add intricated levels of such scripts?
<maxzor> I have a file that is lz4 compressed and holds zlib compressed chunks
<rafasc> a script is a script. You can do whatever you want.
<rafasc> But if you have a way to convert a file into text, the proper way is to use textconv attributes.
<rafasc> git converts both files to text, then perform a normal text-diff on the result.
<maxzor> Do such scripts play nicely with git rebase, merge, etc?
<rafasc> the textconv is just for visualization.
<maxzor> So the hooks from that tool make sense
<maxzor> To effectively do SCM on the human-readable basis
<rafasc> not necessarily. Because you can define merge drivers, to merge your binary content.
<maxzor> rafasc, will look into it, thank you
<rafasc> maxzor: it's not clear if the actions they're doing on your files is reversible. I'd rather add the files, and deal with visualization/merge drivers than transpiring them into another format back and forward.
<maxzor> rafasc, +1
```
