### ISSUE TITLE
Cooking Overhaul

### ISSUE THREAD

**Issue by rfuzzo** [Traderain/Wolven-kit#204]
**Is your feature request related to a problem? Please describe.**
Right now, cooking is done outside the wcc_lite r4data directory (the depot). Cooking uncooked assets that way will throw many missing imports errors because wcc_lite cook doesn't find the uncooked file dependencies. 

**Describe the solution you'd like**
Implement an oppan-rmemr-style way of cooking:

1.  cook textures the old way
`cook -platform=pc -mod="%DIR_UNCOOKED_TEXTURES%" -basedir="%DIR_UNCOOKED_TEXTURES%" -outdir="%DIR_COOKED_DLC%"`
- and move the cook.db to a specific folder to use later in wcc buildcache texture

2. cook all other assets (bundles) differently:
`cook -platform=pc -trimdir="dlc\dlc%MODNAME_LC%" %WCC_SEEDFILES% -outdir="%DIR_COOKED_DLC%"`
- where trimdir is a path to a virtual link to the modproject (creating links is already implemented in the radish-crossover, so we just need to use it here)
- and seedfiles: I don't know... wait for rmemr to answer
- and move the cook.db to a specific folder to use later in wcc buildcache collision

3. fix the cook.db file paths in buildcache

**Unknowns**
- do we need to cook the collision cache files seperatly too? what about the cook db?
- what about copying files pre and post cooking from the mod project to the cooked directory? (buffers pre-cooking, files that aren't copied by wcc cook post-cooking)

**Comment by Maxzor** [comment]
I think @rmemr's mountpoint solution to "put" his mod folders inside the modkit r4data is pretty neat. No better workflow that I know of.
