### ISSUE TITLE
rework way of displaying cr2w in frmChunkList

### ISSUE THREAD

**Issue by rfuzzo** [Traderain/Wolven-kit#210]
I plan to rework a bit the tabular way of displaying cr2w in frmChunkList
![deep_parser](https://user-images.githubusercontent.com/16599683/90775247-e762cc80-e2f8-11ea-8e48-d0be29e4144b.png)
Currently the ruler is parentID. It does not go well with references (handles, imports, etc.).
I think of a virtualParentID to use instead.

_Originally posted by @Maxzor in https://github.com/Traderain/Wolven-kit/issues/61#issuecomment-677662024_

**Comment by Maxzor** [comment]
40b482acc596a45ee0ad03ced81f2541abc0b616
https://github.com/Traderain/Wolven-kit/commits/chunk-auto-parenting-enhanced-temp-WIP-no-base-on-no-merge

Reparents on a VirtualParentChunkId used so far only to display the chunk tree in frmChunkList.
The base is the export table parentId. Enhanced with CPtr and CHandle. 
It is there mostly to reparent dangling chunks, but also forces reparenting on corner cases, CHardAttachment for example, for readability.

Dangling chunks are Classes upper CObject in the OOP graph, e.g. IScriptable.
CVariable --> IReferencable --> ISerializable --> IScriptable --> CObject
They cannot be parented to dowcasts (CObject) during serialization to cr2w, so their parentId is null (0).
Yet they can be reattached properly to the chunk tree using the above described reparenting.

**Comment by Maxzor** [comment]
#224

**Comment by Maxzor** [comment]
Done
