### ISSUE TITLE
Integrate Irrlicht into the project

### ISSUE THREAD

**Issue by Traderain** [Traderain/Wolven-kit#216]
Add these to the project as a separate solution:
 - https://github.com/vonLeebpl/WKIrrlicht
 - https://github.com/vonLeebpl/WKIrrlichtLime
Because if these repos get deleted the whole renderer part of Wkit will break

**Comment by Traderain** [comment]
Implemented in 446b7ba7e9f7637355d057ee170ff9c478957484

**Comment by Traderain** [comment]
We should probably do this better...

**Comment by michaelpolakatwork** [comment]
https://github.com/michaelpolakatwork/Wolven-kit now has both WKIrrlicht and WKIrrlicht.Lime added to the main solution (with fixes and customizations to get xbm support and materials working)

**Comment by michaelpolakatwork** [comment]
master branch on my fork...

**Comment by Traderain** [comment]
@michaelpolakatwork Awesome! Looking forward to the pull request. :) keep up the good work
