### ISSUE TITLE
File editor wont save a file outside of a project

### ISSUE THREAD

**Issue by duffremle** [Traderain/Wolven-kit#235]
**Describe the bug**
Without having created a project I can open, in this case, a .w2l file and edit it. When I try to save the edited .w2l file using the save icon on the sidebar nothing happens. The file is not saved and the output area at the bottom of the ui doesnt give any message. Also on the File menu the Save & Save All buttons are greyed out. 

If I create a project & copy the file I want to edit to it, after editing it saves just fine.  

**Expected behavior**
Since it lets me open & edit a file that's not part of a project, it seems like it should also let me save it afterward. I have been using a version from 2018 before this & it would let me do this. 

**Desktop (please complete the following information):**
 - OS: Win 7
 - Browser Firefox, version 80
 - Version of WolvenKit v0.6.1 

**Additional context**
Obviously this version is much improved from 2018, it will open many files that the 2018 version would crash on & has alot more features. But it would be great to not have to make a project to be able to do some simple stuff like edit a .w2l or .w2ent file.

**Comment by rfuzzo** [comment]
addon: I added opening cr2w files with WolvenKit in Explorer
video demo:
https://streamable.com/79kb9h
