### ISSUE TITLE
Return of the x to close the file on each open file's tab

### ISSUE THREAD

**Issue by duffremle** [Traderain/Wolven-kit#243]
**Is your feature request related to a problem? Please describe.**
It's not related to any problem. In the 2020.06.15 version each open file had an x for closing that file on its file tab (screenshot below). That doesnt seem to be in v0.7. 

**Describe the solution you'd like**
It's just a nice little usability feature I'd like to see come back.

**Screenshots**
What i'm referring to is highlighted with a red 'circle' in the screenshot
![bring the x back](https://user-images.githubusercontent.com/71484892/93738359-32e3f100-fbab-11ea-85fe-83060e9c2303.jpg)

I should have included a screenshot of how v0.7 looks for me, here's one now. This is on win7. 
![v0 7 no x for me](https://user-images.githubusercontent.com/71484892/93830058-c7466600-fc34-11ea-8a6f-f2a7a800fc4e.jpg)

x's are back for me, as far as i'm concerned this is now a closed issue.
![the x is back](https://user-images.githubusercontent.com/71484892/93991888-7462d080-fd52-11ea-8975-1d55c3f5c613.jpg)

.

**Comment by rfuzzo** [comment]
![the x is back](https://cdn.discordapp.com/attachments/532643731271188503/757496313909608448/unknown.png)

hmm, I definitely have the x...
