### ISSUE TITLE
0.7 Release Bugs

### ISSUE THREAD

**Issue by ja-to** [Traderain/Wolven-kit#246]
List of bugs/issues that should be fixed before publishing the next major WolvenKit release.

**Issues**

- [x] Additional testing for Maxzor's CR2W chunk editing overhaul . Maxzor has nailed every bug I reported very quickly, but we need more users testing to find critical bugs.

- [x] Fix hotkey crashes. Currently, hotkeys such as ctrl+c, ctrl+v, delete, etc. cause crashes when editing strings in CR2W files. It seems like the way hotkeys work needs to be refactored. Perhaps we 'ought to just disable chunk editing hotkeys for now to get 0.7 finished.

- [x] Adding files as DLC from asset browser doesn't trim off the existing DLC paths. This leads to extremely confusing file paths. e.g. user has existing structure such as dlc/dlccustomswordproject/data/meshes... etc. and wants to add a cooked sword mesh from BOB. The cooked sword mesh will be added as follows: dlc/dlccustomswordproject/dlc/bob/data/items/weapons/etc... I suggest when adding from DLC bundles and adding as DLC, we trim the dlc/bob/ folders off. As far as I know, vanilla DLC always has two subfolders that should be trimmed from the base dir.

- [x]  Some parts of WolvenKit reference old icons occasionally, such as the icon Discord uses to show the application. Icons should be consolidated to minimize reused assets and make it easier to change them in the future.

- [x]  Improve list of externally handled files to make Project Explorer more usable. i.e. .blend files, .apx files, .3dsmax files

- [x] Opening uncooked xbm files results in unhandled exception.

- [x]  Project Explorer (formerly mod explorer) freezes when adding too many files, such as a Radish directory. To repeat, add a few thousand files and watch WolvenKit suffer. Perhaps a check for pending update count could be added? Where if more than 999 files are added, instead of trying to update the Project Explorer simply reloads?

- [x] Project fails to build completely with uncooked directory. The build is stalled after the cooking process, and WolvenKit must be restarted. Currently broken in master build, works as expected with Terrain Renderer branch.

- [x] Raw folder should always deploy a Mod and DLC subfolder to improve Import Utility usability. Currently only the Raw/Mod folder is deployed on startup.

- [x]  Import Utility Scroll resets to the top with any changes. This makes importing assets near the bottom of the directory very tedious. Sort by file type results in crash. (disabled this option for now) Open folder button breaks scaling on high DPI monitors.

- [x] Witcher 3 Modding Tool License button results in crash. (disabled button for now)

- [x]  There's some issue regarding persistent layout. When editing w2w files, some combination of window arrangements renders WolvenKit unable to display anything for w2w files, even after relaunch. The layout config files must be deleted to restore functionality.

- [x]  Recent file list sorts by oldest first. Additionally, new w3modproj files are not added to recent files. Seems like recent files are limited to 5? Could be a little longer.

- [x] *New* Opening a w3modproj with Welcome Form that's changed locations or been deleted results in unhandled exception.

**Comment by rfuzzo** [comment]
- [ ] register all (new) mods when the mod asset browser opens... right now it only registers mods on app startup

**Comment by rfuzzo** [comment]
- [ ] enable collision cache for improved lexar abilities

**Comment by ja-to** [comment]
I updated the issues a bit. I should be able to take care of the image resources mess and the external file list in the very near future.

**Comment by rfuzzo** [comment]
All reported bugs resolved. More testing is adressed here: #205

**Comment by sodanakin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Github](https://trello.com/c/V52duEWM/16-github)
