### ISSUE TITLE
Add the ability to set global variables using the debugging protocol

### ISSUE THREAD

**Issue by ali-alidoust** [Traderain/Wolven-kit#46]
The packet format for setting a variable is as follows (w3net style):
```
Request()
    .utf8("Config")
    .int32(0xCC00CC00) # magic number
    .utf8("set")
    .utf8(section)     # Section
    .utf8(name)        # Variable Name
    .utf16(value)      # Variable Value
    .end()
```

I think a PropertyGrid filled with all vars received by using the "list" command and ability to change the values using this command could be really useful.

**Comment by Traderain** [comment]
Thanks I'll implement it later today. I was wondering how it works and didn't really have time to experiment with it.
