### ISSUE TITLE
Mod manager

### ISSUE THREAD

**Issue by Traderain** [Traderain/Wolven-kit#48]
So since Nexus Mod Manager (aka NMM) is pretty horrible with handling Witcher 3 mods I think we should create our own thing.
By looks and function I would say something like the [Gta V mod manager](https://hu.gta5-mods.com/tools/gtav-mod-manager) would be good for us.

Features we definetely need:

- Virtual file system handling
- Calling script merger and Mod merger to check for conflicts when trying to install
- The installer package system needs to be upgraded a bit so version description etc. can be added into it.
- #33 needs to be finished so files can be inspected without reading bundles.
- We need to inspect how the Nexus API works in NMM (maybe ask for permission from them) and make NMM links to be openable in WolvenKit mod manager.

The basic layout is started in /.ModManager. Will require some work from both WolvenKit's side and ModManager's side before it can actually replace NMM but since we don't need to support multiple games it will probably be done in a couple weeks.

**Comment by SkacikPL** [comment]
Since CDReject is lazy and probably will never fix default script recompilation, first and easiest feature to implement would probably a fix to the content0/scripts/game/r4game.ws thePlayer.RemoveAllNonAutoBuffs( , true ); call (remove the coma).

There, tool of the year.

**Comment by Traderain** [comment]
@SkacikPL Here is the file of the year in that case:
```csharp
var old = File.ReadAllLines(Path.Combine(GamePath) + "..\\..\\.\\content0/scripts/game/r4game.ws");
old[1671] = "thePlayer.RemoveAllNonAutoBuffs( true );";
File.WriteAllLines(Path.Combine(GamePath) + "..\\..\\.\\content0/scripts/game/r4game.ws",old);
```

**Comment by Traderain** [comment]
Something similar to this would be perfect: https://github.com/loot/loot

**Comment by Traderain** [comment]
@ChiefyWombat's or that other guy's manager from the forums should do it. The package installer is gonna be easy to use and it keeps an uninstall log so its not hard to uninstall.
