### ISSUE TITLE
Figure out all the unknown bytes and parse files properly

### ISSUE THREAD

**Issue by Traderain** [Traderain/Wolven-kit#5]
| Status | Extension| Type | Progress                                                                                         |
|--------|----|---------|-----------------------------------------------------------------------------------------------------|
| ✓  |XML | XML File| xml file can be opened in text editors.                                                             |
| ½  |XBM | CR2W file| Fully parsed altought some stuff is not yet correct?                                    |
| ✓  |Wizdef | CR2W file | Parsed fully since there is only one of this and doesnt contain anything might be a test file  |
| ✓  |W3Simplex | CR2W file | Parsed fully contains simplex data                                                          |
| ½  |W3Occulsion | CR2W file | Little stuff is missing contains occulsion data                                           |
| X  |W3Fac | CR2W file | Missing a lot contains skeleton and MimicFace                                                   |
| X  |W3Dyng | CR2W file | Missing a lot contains dyng resource and sekeleton                                             |
| ✓  |W3App | CR2W file | Parsed fully contains appearances                                                               |
| X  |W2W | CR2W file | Missing a lot contains info about how a level is set up                                           |
| ½   |W2Ter | CR2W file | Little stuff is missing contains terrain info                                                  |
| ✓  |W2Steer | CR2W file | Parsed fully contains movement and steering commands                                          |
| ✓  |W2Sf | CR2W file | Parsed fully contains Switchable foliage                                                         |
| ✓  |W2Scene | CR2W file | Parsed fully contains conversation/scene                                                      |
| ½  |W2Rig | CR2W file |Contains rig                                                                      |
| ✓  |W2Ragdoll | CR2W file | Parsed fully lot contains ragdoll data/begaviour                                               |
| ✓  |W2Quest | CR2W file | Parsed fully contains a quest                                                                 |
| ✓  |W2Qm | CR2W file | Parsed fully contains the pins a world                                                           |
| ✓  |W2Phase | CR2W file | Parsed fully contains quest progress                                                          |
| X  |W2P | CR2W file | Missing a lot contains particle system                                                            |
| ✓  |W2Mi | CR2W file | Parsed fully contains material instance                                                          |
| ✓  |W2Mg | CR2W file | Parsed fully contains material graph                                                             |
| ½  |W2Mesh | CR2W file | Missing a lot contains a mesh(es?)                                                             |
| ½  |W2L | CR2W file | Little stuff is missing contains level data                                                       |
| ✓  |W2Job | CR2W file | Parsed fully contains an action/job for an NPC                                                  |
| ✓  |W2Je | CR2W file | Parsed fully contains collection of journal entries                                              |
| X  |W2Fnt | CR2W file | Missing a lot contains a font                                                                   |
| ½  |W2Ent | CR2W file | Little stuff is missing contains entity data                                                    |
| ✓  |W2Em | CR2W file | Parsed fully contains map pins info                                                              |
| ✓  |VBrush | CR2W file | Parsed fully contains a vegetation brush(es)                                                   |
| ✓  |Usm | Multiplexed video file | Needs to be demultiplexed to view as a video file                                    |
| X  |Textarray | CR2W file | Missing a lot contains a textarray                                                          |
| ✓  |Subs | Text file | Can be opened with any ordinary text editor                                                      |
| X  |Srt | Unknown | Can't parse it (Might be SRT Tree or Speedtree?)                                                    |
| ✓  |Spawntree | CR2W file | Parsed fully contains spawning data                                                         |
| ✓  |Sav | Save file | Parsed fully but not implemented yet and for some random reason there is one in game archives     |
| X  |Redwpset | CR2W file | Missing a lot of stuff contains waypoint collection                                          |
| ✓  |Redswf | CR2W file | Swf stuff and dds images                                   |
| ✓  |Redicsv | CR2W file | Missing a lot contains a 2d array of data                                                     |
| ✓  |Redgame | CR2W file | Parsed fully contains info about game resource                                                |
| ✓  |Redfur | CR2W file | Parsed fully contains Hairworks info probably                                                  |
| X  |Redexp | CR2W file? | Missing a lot of stuff contains Areas                                                         |
| ✓  |Reddlc | CR2W file | Parsed fully contains dlc info                                                                 |
| ½   |Reddest | CR2W file | Little stuff is missing contains Apex destruction info                                       |
| ✓  |Redcloth | CR2W file | Parsed fully contains Apex cloth                                                             |
| ✓  |Redapex | CR2W file | Parsed fully contains Apex destruction info                                                   |
| ✓  |Popup | CR2W file | Parsed fully contains info about a popup                                                        |
| X  |Navtile | Unknown | Not parsed, not even listed by wcc_lite (no idea)                                               |
| X  |Navmesh | Unknown | Not parsed (Probably Navmesh info?)                                                             |
| X  |Naviobstacles | Unknown | Not parsed (probably info about obstacles for NPCs)                                       |
| X  |Navgraph | Unknown | Not parsed (no idea)                                                                           |
| X  |Navconfig | Unknown | Not parsed (maybe pathfinder config for the ai?)                                              |
| ✓  |Menu | CR2W file | Fully parsed contains info about a menu element                                                  |
| ✓  |Journal | CR2W file | Fully parsed contains info about a journal entry                                              |
| ✓  |Hud | CR2W file | Fully parsed contains info about hud elements                                                     |
| ✓  |Guiconfig | CR2W file |Fully parsed contains info about hud elements                                    |
| ✓  |Grassmask | CR2W file | Missing a lot of stuff contains grassmasks                                                  |
| ✓  |Formation | CR2W file | Fully parsed contains (ai preset? behaviour?)                                               |
| ✓  |Flyr | CR2W file | Fully parsed contains tree info                                                   |
| ✓  |Env | CR2W file | Fully parsed contains enviroment info                                                             |
| ✓  |Csv | Csv file | Can be opened in Microsoft Excel                                                                   |
| ✓  |Cellmap| CR2W file | Missing a lot of stuff contains Cellmap                                                        |
| ½  |Buffer | Unknown | Animation and model data

**Comment by Traderain** [comment]
Srt files may be parsed with this needs more investigation
https://github.com/Shinigami69/Ark-Dev-Kit_Source/blob/master/Engine/Source/ThirdParty/SpeedTree/SpeedTreeSDK-v7.0/Source/Core/Source/Parser.cpp
It can parse in theory srt 07.0.0

**Comment by Traderain** [comment]
```cpp
private class EntityHandle 
{
        byte 1;
        GUID Existing_CEntity;
        byte[16] Zerobytes;
}
```
by rmemr

**Comment by Traderain** [comment]
xbm could be read with a modified version of this most likely https://gist.github.com/soeminnminn/e9c4c99867743a717f5b

**Comment by Traderain** [comment]
So usm files are a multiplexed combination of a single m2v file and a couple hca files as the sound.
I tought they are adx files but after checking the IDString and investigating it is actually a hca file. Might be XOR-ed as most scaleform stuff nowadays.

**Comment by Traderain** [comment]
So except xbm (but once dds header is fixed that is done too) and .cache files now everything is parsed properly. soundspc.cache is bugged still but will be hopefully fixed soon. Sadly Dep.cache&Shader.cache and collision.cache can't really be parsed since they are binary but I started dissasembling witcher 3 for clues how to parse them. Navmes files and such are not important at the moment so after soundcache is fixed particle files should be the next thing to finish.

**Comment by Traderain** [comment]
In ad3758fea5c6ddba3c1e1313868aeabcfbe976f0 added all the CNames and Vectors which are in the game.

**Comment by Traderain** [comment]
Created a yara rule to find the mw of files (also some common witcher stuff): https://gist.github.com/Traderain/d6d780f294271427408774b4adea8271
Also created a program to dump given folders files with wcc_lite: https://gist.github.com/Traderain/d6d780f294271427408774b4adea8271
Gonna try to dump the whole game into XMLs and merge them by classes so we can generate classes from it and read files by going through the fields of the class with reflection. IIRC Rick did this in Gibbed.RED for Witcher 2.

**Comment by Traderain** [comment]
Implemented w2ragdoll files b1592a8c1418afdeb08b0adfb9d966eac626aef2

**Comment by Traderain** [comment]
Implemented guiconfig 00977e7d6d86107186e00c1ee90bc21b2b62eb5b

**Comment by Traderain** [comment]
Implemented all the unknownbytes Flyr files 9863e107146226b07fa302cc5ea4509117e671c3

**Comment by Traderain** [comment]
Current state of files:
(w3occulsion) CUmbraTile  - Defereddatabuffer needs to be figured out.
(XBM) CBitmapTexture - No idea what the fuck is going on. Ask Lim3zer0 for progress.
(w2w) CLayerInfo - HasEmbededLayerInfo Parsing no idea what the hell that is. Some byte array we need to magically parse.
(w2ter) CTerrainTile - Some bytes about the file? This might be some bumpmap or whatever about the terrain?
(w2rig) CSkeleton - Needs a bunch of shit. Multiple types have this.
(w2p) CParticleSystem - Some stuff is missing in CParticleEmitter and something is wrong with CParticleSystem but I'm really close.
(w2mesh) CMesh - Something is sketchy here. Might be able to figure it out. After all we can render it.
(w2l) The data buffer in CSectorData needs to be figured out. Otherwise its gonna be good to go.
(w2beh) Many classes many unknown stuff. This file is horrible honestly.
(w2fnt) W2Font - Same as xbm. Cancer.
(w2ent) This is some next level cancer. Need to figure out what the hell is actually going on with flatcompileddata.
(redwpset) CWayPointsCollection - Doable just takes a lot of effort. Gonna do it soon hopefully.
(redexp) Databuffer probably or something like that. It's pure cancer.
(reddest) Databuffer probably or something. Lot of data in this. I suspect something Nvidia related.
<--Navigation stuff--> Pathlib can do this in theory so not needed.
(buffer) Mostly figured out in renderer.

**Comment by Traderain** [comment]
Created unit tests for the CR2W Files:
![image](https://user-images.githubusercontent.com/6411732/75096783-41314680-55a3-11ea-825c-5490c9ac97bc.png)

**Comment by Traderain** [comment]
Current not fully parsed 43/65:  
 - [ ] w2fnt:
    - [ ] CFont
 - [ ] redwpset
   - [ ] CWayPointsCollection 
 - [ ] redexp
   - [ ] CCookedExplorations 
 - [ ] w2animev 
   - [ ] CExtAnimEventsFile 
 - [ ] w2cube 
   - [ ] CCubeTexture 
 - [ ] w2ter 
   - [ ] CTerrainTile 
 -  [ ] redswf ??? something funky here
 - [ ] reddest
   - [ ] CPhysicsDestructionResource 
- [ ] w2rig
   - [ ] CSkeleton 
- [ ] texarray
   - [ ] CTextureArray 
- [ ] w2p
   - [ ] CParticleEmitter 
- [ ] w3dyng
   - [ ] CSkeleton 
-  [ ] w2w
   - [ ] MANY MANY STUFF but already figured out by rmemr
- [ ] w2beh
   - [ ] CBehaviorGraph 
   - [ ] CBehaviorGraphTopLevelNode 
- [ ] w3fac 
   - [ ] CSkeleton
- [ ] w2mesh
   - [ ] CMesh 
- [ ] w2l
   - [ ] MANY MANY STUFF also figured out by rmemr mostly
- [ ] w2anims 
   - [ ] CSkeletalAnimationSet 
   - [ ] CSkeletalAnimation 
- [ ] w2ent
   - [ ] many classes :(
- [ ] w2cutcsene
   - [ ] many classes

**Comment by rfuzzo** [comment]
last unparsed class left:
- [ ] CCameraCompressedPose

**Comment by Traderain** [comment]
Do you have some example files which contain the class? I'll investigate
it. I wana close this once and for all.

rfuzzo <notifications@github.com> ezt írta (időpont: 2020. máj. 4., H,
11:20):

**Comment by rfuzzo** [comment]
yeah here: \animations\camera\camera_animations.w2anims
