### ISSUE TITLE
Nexusmods API

### ISSUE THREAD

**Issue by Traderain** [Traderain/Wolven-kit#56]
So I was thinking about implementing the basics of nexusmods since it wouldn't really be hard so you can upload your mod after you are done and would be nice for the mod manager too I guess. It should be discussed if its worth the time it takes to implement it.

**Comment by ChiefyWombat** [comment]
I agree this needs to be in the mod manager and I'm writing DarkOne and Tannin today about it. I'll post what information they give me.

**Comment by Traderain** [comment]
I realized this is out of scope. The mod manager should be responsible for this.
