### ISSUE TITLE
Assets browser crash

### ISSUE THREAD

**Issue by djkovrik** [Traderain/Wolven-kit#64]
**Steps to reproduce bug:**
Right click on any folder in Mod explorer -> Add file

It opens empty Asset browser window (so it is not possible to add files to chosen folder directly) which crashes when you click on that top text edit field.
```
System.NullReferenceException: Object reference not set to an instance of an object.
in WolvenKit.frmAssetBrowser.pathPanel_Click(Object sender, EventArgs e)
in System.Windows.Forms.Control.OnClick(EventArgs e)
in System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
in System.Windows.Forms.Control.WndProc(Message& m)
in System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Traderain** [comment]
Can you please use the "built-in" bug recorder thing. I can't seem to reproduce it. Help->Records steps to reproduce bug.
Thanks for the report tough.
