### ISSUE TITLE
Copy/Pasting text with keyboard shortcuts is now broken.

### ISSUE THREAD

**Issue by KoalaNalle** [Traderain/Wolven-kit#91]
Copying a path from an entity template path  is now broken. Selecting text crtl+c.
And pasting to asset browser path field don't work either.

And will actually brake copy/pasting in windows if wolvenkit is running.

Mouse copy/paste works ofc.

**Comment by Traderain** [comment]
See 3b53a52e4375b6ebcaf5a6f74e475f045b95bb8a. Its just not on nexus yet. Didn't have time to post it there.
