### ISSUE TITLE
WCC patcher

### ISSUE THREAD

**Issue by KoalaNalle** [Traderain/Wolven-kit#95]
The reworked wcc patcher did not allow me to run the Wolvenkit, said that I had outdated version.

The exe was already patched. File is available here:
https://drive.google.com/file/d/1_N0EJavwUUIDQhytpkA8A66bxc55InC4/view?usp=sharing

I think I have the second community patch with in that also.

Also the patcher should make a backup file of the original, unpatched version.

**Comment by Traderain** [comment]
I will have to check that didn't know people actually use that. Well you can just reinstall so I don't see the point to actually backup but I can do that of course.
