### ISSUE TITLE
Keep State across restarts

### ISSUE THREAD

**Issue by philippTheCat** [Traderain/Wolven-kit#99]
**Is your feature request related to a problem? Please describe.**

When developing wolven-kit it is annoying to re-open the mod, find the file I currently need.

**Describe the solution you'd like**
Wolven-Kit should save the current layout, open mod/files etc when shutting down, and reload this state when starting up.

**Comment by Traderain** [comment]
Thanks for the suggestion. This shouldn't be hard. I will implement it as soon as I can.

**Comment by Traderain** [comment]
Implemented in de5d8c0
